[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
build_flags =
  -D WIFI_SSID=\"ATT7ugu78B\"
  -D WIFI_PASS=\"58y#j78tai23\"
  -D DEVICE_ID=\"esp32-1\"
